import pandas
import requests
from bs4 import BeautifulSoup

cats = [
    "https://www.ace-ace.de/de/produkte/daempfungstechnik.html",
    "https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung.html",
    "https://www.ace-ace.de/de/produkte/schwingungstechnik.html",
    "https://www.ace-ace.de/de/produkte/sicherheitsprodukte.html"
]

# sub_cats = []
#
# for cat in cats:
#     resp = requests.get(cat)
#     soup = BeautifulSoup(resp.content, "html.parser")
#     links = [a["href"] for a in soup.select(".subcategory__title")]
#     sub_cats.extend(links)
#     print(cat)
#     print(len(sub_cats))
#
# print(len(sub_cats))
# print(sub_cats)

sub_cats = [
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/stossdaempfungsplatten.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/tuerdaempfer.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer.html'

]

# sub_sub_cats = []
#
# for sub_cat in sub_cats:
#     resp = requests.get(sub_cat)
#     soup = BeautifulSoup(resp.content, "html.parser")
#     links = [a["href"] for a in soup.select(".subcategory__title")]
#     sub_sub_cats.extend(links)
#     print(sub_cat)
#     print(len(sub_sub_cats))
#
# print(len(sub_sub_cats))
# print(sub_sub_cats)

cats_level_5 = [
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc5-bis-mc75.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc150-bis-mc600.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc150-v4a-bis-mc600-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pmcn150-bis-pmcn600.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pmcn150-v4a-bis-pmcn600-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc190-bis-sc925.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc-25-bis-sc-190.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc-300-bis-sc-650.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pet20-bis-pet27.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-bis-mc64.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-v4a-bis-mc64-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-ht-bis-mc64-ht.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-lt-bis-mc64-lt.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/sc33-bis-sc45.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/ma-ml33-bis-ma-ml64.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-ta.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-ts.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-tr.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-tr-h.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-tr-l.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-tr-hd.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/stossdaempfungsplatten/slab-030-bis-slab-300.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p60.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p90.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p100.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p160.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p260.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-h350.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-h1200.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-e20.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-e50.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-e100.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-e600.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gst-40-tandem.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-bis-gz-40.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-v4a-bis-gz-40-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/dvc-32.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hbd-50-bis-hbd-85.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hbs-28-bis-hbs-70.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hb-12-bis-hb-70.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/tuerdaempfer/td-tde.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/vc25.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-e2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-g2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-c2-und-frn-c2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-d2-und-frn-d2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-f2-k2-und-frn-f2-k2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fdt.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fdn.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-p1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-n1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-u1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-s1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyt-h1-und-fyn-h1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyt-la3-und-fyn-la3.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/slab-170-bis-slab-275.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/cel.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/pad.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/levelling-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/soft-bell-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/light-bell-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/hard-bell-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/marine-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/cone-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/bubble-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/all-attitude-mounts.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/flex-locs.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/plm.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-3-bis-pal-9.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/scs33-bis-scs64.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/tubus-tc-und-tc-s.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/tubus-ti.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/crash-daempfer.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-pl.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-plk.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-sl.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-slk.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-lz-p.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-pn.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-prk.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-r.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer/vs.html'
]

# l6_cats = []
#
# for c in cats_level_5:
#     resp = requests.get(c)
#     soup = BeautifulSoup(resp.content, "html.parser")
#     links = [a["href"] for a in soup.select("li.catmenu__level-6 a")]
#     l6_cats.extend(links)
#     print(c)
#     print(len(l6_cats))
#
# print(len(l6_cats))
# print(l6_cats)


l6_cats = [
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc5-bis-mc75/mc5eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc5-bis-mc75/mc9eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc5-bis-mc75/mc10eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc5-bis-mc75/mc25eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc5-bis-mc75/mc30eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc5-bis-mc75/mc75eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc150-bis-mc600/mc150eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc150-bis-mc600/mc225eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc150-bis-mc600/mc600eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc150-v4a-bis-mc600-v4a/mc150eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc150-v4a-bis-mc600-v4a/mc225eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/mc150-v4a-bis-mc600-v4a/mc600eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pmcn150-bis-pmcn600/pmcn150eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pmcn150-bis-pmcn600/pmcn225eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pmcn150-bis-pmcn600/pmcn600eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pmcn150-v4a-bis-pmcn600-v4a/pmcn150eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pmcn150-v4a-bis-pmcn600-v4a/pmcn225eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pmcn150-v4a-bis-pmcn600-v4a/pmcn600eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc190-bis-sc925/sc190eum-0-bis-4.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc190-bis-sc925/sc300eum-0-bis-4.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc190-bis-sc925/sc650eum-0-bis-4.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc190-bis-sc925/sc925eum-0-bis-4.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc-25-bis-sc-190/sc25eum-5-bis-7.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc-25-bis-sc-190/sc75eum-5-bis-7.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc-25-bis-sc-190/sc190eum-5-bis-7.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc-300-bis-sc-650/sc300eum-5-bis-9.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/sc-300-bis-sc-650/sc650eum-5-bis-9.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900/ma30eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900/ma50eum-b.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900/ma35eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900/ma150eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900/ma225eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900/ma600eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900/ma900eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/ma30-bis-ma900/fa1008vd-b.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pet20-bis-pet27/pet27eum-880.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pet20-bis-pet27/pet27eum-nb.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pet20-bis-pet27/pet27eum-sbuc.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/kleinstossdaempfer/pet20-bis-pet27/pet27eum-qcm-880.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-bis-mc64/mc33eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-bis-mc64/mc45eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-bis-mc64/mc64eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-v4a-bis-mc64-v4a/mc33eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-v4a-bis-mc64-v4a/mc45eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-v4a-bis-mc64-v4a/mc64eum-v4a.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-ht-bis-mc64-ht/mc33eum-ht.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-ht-bis-mc64-ht/mc45eum-ht.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-ht-bis-mc64-ht/mc64eum-ht.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-lt-bis-mc64-lt/mc33eum-lt.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-lt-bis-mc64-lt/mc45eum-lt.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/mc33-lt-bis-mc64-lt/mc64eum-lt.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/sc33-bis-sc45/sc33eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/sc33-bis-sc45/sc45eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/ma-ml33-bis-ma-ml64/ma-ml33eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/ma-ml33-bis-ma-ml64/ma-ml45eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/industriestossdaempfer/ma-ml33-bis-ma-ml64/ma-ml64eum.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca2eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca2eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca2eu-sm-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca3eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca3eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca3eu-s-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca4eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca4eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca4eu-frp-6-gewinde-beidseitig.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/ca2-bis-ca4/ca4eu-s-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a1-1-2eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a1-1-2eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a1-1-2eu-c-schwenkbefestigung.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a1-1-2eu-s-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a2eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a2eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a2eu-sm-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a3eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a3eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/schwere-industriestossdaempfer/a1-1-2-bis-a3/a3eu-s-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-ta/ta.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-ts/ts.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-tr/tr.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-tr-h/tr-h.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-tr-l/tr-l.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/strukturdaempfer/tubus-tr-hd/tr-hd.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/stossdaempfungsplatten/slab-030-bis-slab-300/sl-030-12.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/stossdaempfungsplatten/slab-030-bis-slab-300/sl-030-25.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/stossdaempfungsplatten/slab-030-bis-slab-300/sl-100-12.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/stossdaempfungsplatten/slab-030-bis-slab-300/sl-100-25.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/stossdaempfungsplatten/slab-030-bis-slab-300/sl-300-12.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/stossdaempfungsplatten/slab-030-bis-slab-300/sl-300-25.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p60/p-ps-60.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p60/p-pd-60.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p90/p-ps-90.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p100/p-ps-100.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p100/p-pd-100.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p160/p-ps-160.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p160/p-pd-160.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p260/p-ps-260.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-p260/p-pd-260.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-h350/p-hs-350.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-h1200/p-hs-1200.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-h1200/p-hd-1200.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-e20/p-ed-20.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-e50/p-ed-50.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-e100/p-ed-100.html',
    'https://www.ace-ace.de/de/produkte/daempfungstechnik/palettenstopper/p-e600/p-ed-600.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-8.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-10.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-12.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-15.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-19.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-22.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-28.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-40.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-bis-gs-70/gs-70.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-8-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-10-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-12-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-15-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-19-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-22-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-28-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-40-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-15-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-19-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-22-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-28-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gs-8-v4a-bis-gs-40-va/gs-40-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gasdruckfedern/gst-40-tandem/gst-40.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-bis-gz-40/gz-15.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-bis-gz-40/gz-19.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-bis-gz-40/gz-28.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-bis-gz-40/gz-40.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-v4a-bis-gz-40-va/gz-15-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-v4a-bis-gz-40-va/gz-19-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-v4a-bis-gz-40-va/gz-28-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-v4a-bis-gz-40-va/gz-40-v4a.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-v4a-bis-gz-40-va/gz-19-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-v4a-bis-gz-40-va/gz-28-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/industrie-gaszugfedern/gz-15-v4a-bis-gz-40-va/gz-40-va.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/dvc-32/dvc-32eu.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/dvc-32/dvc-32eu-xx.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hbd-50-bis-hbd-85/hbd-50.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hbd-50-bis-hbd-85/hbd-70.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hbd-50-bis-hbd-85/hbd-85.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hbs-28-bis-hbs-70/hbs-28.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hbs-28-bis-hbs-70/hbs-35.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hbs-28-bis-hbs-70/hbs-70.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hb-12-bis-hb-70/hb-12.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hb-12-bis-hb-70/hb-15.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hb-12-bis-hb-70/hb-22.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hb-12-bis-hb-70/hb-28.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hb-12-bis-hb-70/hb-40.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/hydraulische-bremszylinder/hb-12-bis-hb-70/hb-70.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/tuerdaempfer/td-tde/tde-28.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/tuerdaempfer/td-tde/td-28.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/vc25/vc25euft.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/vc25/vc25euf.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc/ma30eum.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc/ma50eum-b.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc/ma35eum.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc/ma150eum.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc/mvc225eum.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc/mvc600eum.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc/mvc900eum.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/vorschub-oelbremsen/fa-ma-mvc/fa1008v-b.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-e2/frt-e2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-e2/frt-e2-g1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-g2/frt-g2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-g2/frt-g2-g1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-c2-und-frn-c2/frt-c2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-c2-und-frn-c2/frt-c2-g1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-c2-und-frn-c2/frn-c2-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-c2-und-frn-c2/frn-c2-r-g1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-c2-und-frn-c2/frn-c2-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-c2-und-frn-c2/frn-c2-l-g1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-d2-und-frn-d2/frt-d2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-d2-und-frn-d2/frt-d2-g1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-d2-und-frn-d2/frn-d2-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-d2-und-frn-d2/frn-d2-r-g1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-d2-und-frn-d2/frn-d2-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-d2-und-frn-d2/frn-d2-l-g1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-f2-k2-und-frn-f2-k2/frt-f2-k2.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-f2-k2-und-frn-f2-k2/frn-f2-k2-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/frt-f2-k2-und-frn-f2-k2/frn-f2-k2-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd/ffd-ss-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd/ffd-ss-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd/ffd-fs-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd/ffd-fs-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd/ffd-sw-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd/ffd-sw-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd/ffd-fw-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/ffd/ffd-fw-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fdt/fdt.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fdn/fdn-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fdn/fdn-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-p1/fyn-p1-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-p1/fyn-p1-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-n1/fyn-n1-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-n1/fyn-n1-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-u1/fyn-u1-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-u1/fyn-u1-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-s1/fyn-s1-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyn-s1/fyn-s1-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyt-h1-und-fyn-h1/fyt-h1.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyt-h1-und-fyn-h1/fyn-h1-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyt-h1-und-fyn-h1/fyn-h1-l.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyt-la3-und-fyn-la3/fyt-la3.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyt-la3-und-fyn-la3/fyn-la3-r.html',
    'https://www.ace-ace.de/de/produkte/geschwindigkeitsregulierung/rotationsbremsen/fyt-la3-und-fyn-la3/fyn-la3-l.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/slab-170-bis-slab-275/sl-170-12.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/slab-170-bis-slab-275/sl-170-25.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/slab-170-bis-slab-275/sl-210-12.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/slab-170-bis-slab-275/sl-210-25.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/slab-170-bis-slab-275/sl-275-12.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/slab-170-bis-slab-275/sl-275-25.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/cel/cel-200.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/cel/cel-300.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsisolierende-platten/pad/pad.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/levelling-mounts/lev.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/soft-bell-mounts/cfbms-1.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/soft-bell-mounts/cfbms-2.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/light-bell-mounts/cfab.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/hard-bell-mounts/cm-vsc1.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/hard-bell-mounts/cm-vsc2.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/hard-bell-mounts/cm-vsc3.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/hard-bell-mounts/cfbmh-1.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/hard-bell-mounts/cfbmh-2.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5250.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5252.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5254.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5251.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5253.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5255.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5216.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5217.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5256.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/com-5257.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/compression-mounts/cf-2.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/marine-mounts/sfm-52010.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/marine-mounts/sfm-52011.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/marine-mounts/sfm-52012.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/marine-mounts/ccfq.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/cone-mounts/cn-12-2.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/cone-mounts/cn-16-1.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/cone-mounts/cn-20.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts/umo-6001.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts/umo-6002.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts/umo-6003.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts/umo-6004.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts/umo-6005.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts/cgm.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts/ctc-2.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/universal-mounts/t.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/bubble-mounts/bm-5064.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/bubble-mounts/bm-5068.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/all-attitude-mounts/aam-5642.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/all-attitude-mounts/aam-5220.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/schwingungsdaempfer/flex-locs/fl-q.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/plm/plm.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-3-bis-pal-9/pal-3.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-3-bis-pal-9/pal-5-5.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-3-bis-pal-9/pal-9.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-18.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-21.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-36.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-55.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-75.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-133.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-255.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-416.html',
    'https://www.ace-ace.de/de/produkte/schwingungstechnik/luftfedern/pal-18-bis-pal-1000/pal-1000.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/scs33-bis-scs64/scs33eu.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/scs33-bis-scs64/scs45eu.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/scs33-bis-scs64/scs64eu.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh38eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh38eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh38eu-s-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh50eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh50eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh50eu-s-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh63eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh63eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdh38-bis-sdh63/sdh63eu-s-fussbefestigung.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp63eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp63eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp80eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp80eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp100eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp100eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp120eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp120eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp160eu-f-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsstossdaempfer/sdp63-bis-sdp160/sdp160eu-r-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/tubus-tc-und-tc-s/tc.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/tubus-tc-und-tc-s/tc-s.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/tubus-ti/ti-1-balg.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/tubus-ti/ti-2-baelge.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/tubus-ti/ti-3-baelge.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/crash-daempfer/cd-20.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/crash-daempfer/cd-21.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/crash-daempfer/cd-38.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/crash-daempfer/cd-63.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/sicherheitsdaempfer/crash-daempfer/cd-88.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-pl/pl.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-plk/plk.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-sl/sl.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-slk/slk.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-lz-p/lz-p.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-pn/pn.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-prk/prk.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-r/r.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/klemmelemente/locked-r/r-z.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer/vs/vs-ba1-fc-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer/vs/vs-ba1-fa-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer/vs/vs-ba5-fc-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer/vs/vs-ba5-fa-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer/vs/vs-bxlr-fc-flansch-frontseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer/vs/vs-bxlr-fa-flansch-rueckseite.html',
    'https://www.ace-ace.de/de/produkte/sicherheitsprodukte/viskoelastische-stossdaempfer/vs/vs-balr-fc-flansch-frontseite.html'
]

product_links = []

for c in l6_cats:
    resp = requests.get(c)
    soup = BeautifulSoup(resp.content, "html.parser")
    links = [a["href"] for a in soup.select(".catmenu__table a")]
    product_links.extend(links)
    print(c)
    print(len(product_links))

print(len(product_links))

pandas.DataFrame(product_links).to_csv(
    "/home/sana451/PycharmProjects/scrapy_parsers/ace_ace_de/ace_ace_de/results/ace-ace.de.links2.csv",
    index=False)
